title: Shib Kumar Saraf
logo: https://github.com/shib1111111.png
description: >-
  Senior Business Analyst & AI Engineer specializing in Agentic Workflows,
  RAG Architectures, and Computer Vision.
theme: jekyll-theme-minimal
google_analytics: # Add your UA-ID here if you have one
show_downloads: true